#ifndef PLYGRD_MASSMATRIX_INTEGRAL_H
#define PLYGRD_MASSMATRIX_INTEGRAL_H

// Implementations are generated by massmatrix_integral.py

double I_1(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_x(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_y(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_z(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_xx(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_yy(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_zz(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_xy(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_xz(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);
double I_yz(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3);

#endif  // PLYGRD_MASSMATRIX_INTEGRAL_H