#ifndef PLYGRD_ORTHOGONAL_IP
#define PLYGRD_ORTHOGONAL_IP

#include <Eigen/Eigen>

// Implementations generated by orthogonal_ip.py
double ip_orthogonal(Eigen::Vector<double,12> q);

Eigen::Vector<double,12> grad_orthogonal(Eigen::Vector<double,12> q);

Eigen::Matrix<double,12,12> hess_orthogonal(Eigen::Vector<double,12> q);

#endif  // PLYGRD_ORTHOGONAL_IP